// @algorithm Dueling Generators
// @category Pseudo-Random Generation / Bitwise Comparison
// @input Two initial seed values for generators A and B
// @problem
//   Compare lower 16 bits of values generated by two LCGs
// @generators
//   A: value = (value * 16807) % 2147483647
//   B: value = (value * 48271) % 2147483647
// @parts
//   Part1: Compare 40,000,000 generated pairs
//   Part2: Compare 5,000,000 pairs with divisibility constraints
// @rules
//   Part2:
//     - Generator A must produce values divisible by 4
//     - Generator B must produce values divisible by 8
// @technique
//   - Linear Congruential Generator (LCG)
//   - Bitmask comparison using (value & 0xFFFF)
//   - Loop with filtering via do/while for constrained generation
// @data-structures
//   - 64-bit integers (long)
// @complexity
//   Part1: O(40,000,000)
//   Part2: O(5,000,000 + rejected generations)
//   Space: O(1)
// @notes
//   - Only the lowest 16 bits are compared
//   - Uses modulus 2^31 - 1 (Mersenne prime)
//   - Filtering significantly reduces effective throughput in Part2

await Part1();
await Part2();
return;

async Task Part1()
{
    var lines = await File.ReadAllLinesAsync("input.txt");
    var a =  long.Parse(lines[0].Split(" ").Last());
    var b = long.Parse(lines[1].Split(" ").Last());
    var count = 0;
    for (int i = 0; i < 40_000_000; i++)
    {
        a = GenA(a);
        b = GenB(b);
        if ((a & 0xFFFF) == (b & 0xFFFF))
            count++;
    }
    Console.WriteLine(count);
    
}
const long div = 2147483647;
long GenA(long val) => (val * 16807) % div;
long GenB(long val) => (val * 48271) % div;


async Task Part2()
{
    var lines = await File.ReadAllLinesAsync("input.txt");
    var a =  long.Parse(lines[0].Split(" ").Last());
    var b = long.Parse(lines[1].Split(" ").Last());
    var count = 0;
    for (int i = 0; i < 5_000_000; i++)
    {
        a = GenA2(a);
        b = GenB2(b);
        if ((a & 0xFFFF) == (b & 0xFFFF))
            count++;
    }
    Console.WriteLine(count);
}

long GenA2(long val)
{
    var temp = val;
    do
    {
        temp = (temp * 16807) % div;
    } while (temp % 4 != 0);
    return temp;
}
long GenB2(long val)
{
    var temp = val;
    do
    {
        temp = (temp * 48271) % div;
    } while (temp % 8 != 0);
    return temp;
}